/**
 * Country name or ISO code to ISO 3166-1 alpha-2, for all 196 countries in the
 * location catalogue.
 *
 * Generated from location-data/countries.json, which is the approved source of
 * truth for country data. Regenerate with scripts/generate-country-codes.js if
 * that file changes.
 *
 * This map used to hold two entries, Nigeria and the United States. Anything
 * else fell through to .toUpperCase(), so "United Kingdom" resolved to
 * "UNITED KINGDOM" rather than "GB". Nothing errored: the value was simply a
 * code that could never match a subscriptionPricing/{countryCode} record or a
 * countryAvailability entry, so per-country pricing silently failed for every
 * country except the two listed. The pricing page offers six.
 *
 * Building it from the catalogue rather than adding four more entries by hand
 * means the next country to launch needs no code change at all.
 */
const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  "ad": "AD",
  "andorra": "AD",
  "ae": "AE",
  "united arab emirates": "AE",
  "af": "AF",
  "afghanistan": "AF",
  "ag": "AG",
  "antigua and barbuda": "AG",
  "al": "AL",
  "albania": "AL",
  "am": "AM",
  "armenia": "AM",
  "angola": "AO",
  "ao": "AO",
  "ar": "AR",
  "argentina": "AR",
  "at": "AT",
  "austria": "AT",
  "au": "AU",
  "australia": "AU",
  "az": "AZ",
  "azerbaijan": "AZ",
  "ba": "BA",
  "bosnia and herzegovina": "BA",
  "barbados": "BB",
  "bb": "BB",
  "bangladesh": "BD",
  "bd": "BD",
  "be": "BE",
  "belgium": "BE",
  "bf": "BF",
  "burkina faso": "BF",
  "bg": "BG",
  "bulgaria": "BG",
  "bahrain": "BH",
  "bh": "BH",
  "bi": "BI",
  "burundi": "BI",
  "benin": "BJ",
  "bj": "BJ",
  "bn": "BN",
  "brunei": "BN",
  "bo": "BO",
  "bolivia": "BO",
  "br": "BR",
  "brazil": "BR",
  "bahamas": "BS",
  "bs": "BS",
  "bhutan": "BT",
  "bt": "BT",
  "botswana": "BW",
  "bw": "BW",
  "belarus": "BY",
  "by": "BY",
  "belize": "BZ",
  "bz": "BZ",
  "ca": "CA",
  "canada": "CA",
  "cd": "CD",
  "congo (democratic republic)": "CD",
  "central african republic": "CF",
  "cf": "CF",
  "cg": "CG",
  "congo (republic)": "CG",
  "ch": "CH",
  "switzerland": "CH",
  "ci": "CI",
  "cote d'ivoire (ivory coast)": "CI",
  "chile": "CL",
  "cl": "CL",
  "cameroon": "CM",
  "cm": "CM",
  "china": "CN",
  "cn": "CN",
  "co": "CO",
  "colombia": "CO",
  "costa rica": "CR",
  "cr": "CR",
  "cu": "CU",
  "cuba": "CU",
  "cabo verde": "CV",
  "cv": "CV",
  "cy": "CY",
  "cyprus": "CY",
  "cz": "CZ",
  "czechia (czech republic)": "CZ",
  "de": "DE",
  "germany": "DE",
  "dj": "DJ",
  "djibouti": "DJ",
  "denmark": "DK",
  "dk": "DK",
  "dm": "DM",
  "dominica": "DM",
  "do": "DO",
  "dominican republic": "DO",
  "algeria": "DZ",
  "dz": "DZ",
  "ec": "EC",
  "ecuador": "EC",
  "ee": "EE",
  "estonia": "EE",
  "eg": "EG",
  "egypt": "EG",
  "er": "ER",
  "eritrea": "ER",
  "es": "ES",
  "spain": "ES",
  "et": "ET",
  "ethiopia": "ET",
  "fi": "FI",
  "finland": "FI",
  "fiji": "FJ",
  "fj": "FJ",
  "fm": "FM",
  "micronesia": "FM",
  "fr": "FR",
  "france": "FR",
  "ga": "GA",
  "gabon": "GA",
  "gb": "GB",
  "united kingdom": "GB",
  "gd": "GD",
  "grenada": "GD",
  "ge": "GE",
  "georgia": "GE",
  "gh": "GH",
  "ghana": "GH",
  "gambia": "GM",
  "gm": "GM",
  "gn": "GN",
  "guinea": "GN",
  "equatorial guinea": "GQ",
  "gq": "GQ",
  "gr": "GR",
  "greece": "GR",
  "gt": "GT",
  "guatemala": "GT",
  "guinea-bissau": "GW",
  "gw": "GW",
  "guyana": "GY",
  "gy": "GY",
  "hn": "HN",
  "honduras": "HN",
  "croatia": "HR",
  "hr": "HR",
  "haiti": "HT",
  "ht": "HT",
  "hu": "HU",
  "hungary": "HU",
  "id": "ID",
  "indonesia": "ID",
  "ie": "IE",
  "ireland": "IE",
  "il": "IL",
  "israel": "IL",
  "in": "IN",
  "india": "IN",
  "iq": "IQ",
  "iraq": "IQ",
  "ir": "IR",
  "iran": "IR",
  "iceland": "IS",
  "is": "IS",
  "it": "IT",
  "italy": "IT",
  "jamaica": "JM",
  "jm": "JM",
  "jo": "JO",
  "jordan": "JO",
  "japan": "JP",
  "jp": "JP",
  "ke": "KE",
  "kenya": "KE",
  "kg": "KG",
  "kyrgyzstan": "KG",
  "cambodia": "KH",
  "kh": "KH",
  "ki": "KI",
  "kiribati": "KI",
  "comoros": "KM",
  "km": "KM",
  "kn": "KN",
  "saint kitts and nevis": "KN",
  "kp": "KP",
  "north korea": "KP",
  "kr": "KR",
  "south korea": "KR",
  "kuwait": "KW",
  "kw": "KW",
  "kazakhstan": "KZ",
  "kz": "KZ",
  "la": "LA",
  "laos": "LA",
  "lb": "LB",
  "lebanon": "LB",
  "lc": "LC",
  "saint lucia": "LC",
  "li": "LI",
  "liechtenstein": "LI",
  "lk": "LK",
  "sri lanka": "LK",
  "liberia": "LR",
  "lr": "LR",
  "lesotho": "LS",
  "ls": "LS",
  "lithuania": "LT",
  "lt": "LT",
  "lu": "LU",
  "luxembourg": "LU",
  "latvia": "LV",
  "lv": "LV",
  "libya": "LY",
  "ly": "LY",
  "ma": "MA",
  "morocco": "MA",
  "mc": "MC",
  "monaco": "MC",
  "md": "MD",
  "moldova": "MD",
  "me": "ME",
  "montenegro": "ME",
  "madagascar": "MG",
  "mg": "MG",
  "marshall islands": "MH",
  "mh": "MH",
  "mk": "MK",
  "north macedonia": "MK",
  "mali": "ML",
  "ml": "ML",
  "mm": "MM",
  "myanmar": "MM",
  "mn": "MN",
  "mongolia": "MN",
  "mauritania": "MR",
  "mr": "MR",
  "malta": "MT",
  "mt": "MT",
  "mauritius": "MU",
  "mu": "MU",
  "maldives": "MV",
  "mv": "MV",
  "malawi": "MW",
  "mw": "MW",
  "mexico": "MX",
  "mx": "MX",
  "malaysia": "MY",
  "my": "MY",
  "mozambique": "MZ",
  "mz": "MZ",
  "na": "NA",
  "namibia": "NA",
  "ne": "NE",
  "niger": "NE",
  "ng": "NG",
  "nigeria": "NG",
  "ni": "NI",
  "nicaragua": "NI",
  "netherlands": "NL",
  "nl": "NL",
  "no": "NO",
  "norway": "NO",
  "nepal": "NP",
  "np": "NP",
  "nauru": "NR",
  "nr": "NR",
  "new zealand": "NZ",
  "nz": "NZ",
  "om": "OM",
  "oman": "OM",
  "pa": "PA",
  "panama": "PA",
  "pe": "PE",
  "peru": "PE",
  "papua new guinea": "PG",
  "pg": "PG",
  "ph": "PH",
  "philippines": "PH",
  "pakistan": "PK",
  "pk": "PK",
  "pl": "PL",
  "poland": "PL",
  "palestine": "PS",
  "ps": "PS",
  "portugal": "PT",
  "pt": "PT",
  "palau": "PW",
  "pw": "PW",
  "paraguay": "PY",
  "py": "PY",
  "qa": "QA",
  "qatar": "QA",
  "ro": "RO",
  "romania": "RO",
  "rs": "RS",
  "serbia": "RS",
  "ru": "RU",
  "russia": "RU",
  "rw": "RW",
  "rwanda": "RW",
  "sa": "SA",
  "saudi arabia": "SA",
  "sb": "SB",
  "solomon islands": "SB",
  "sc": "SC",
  "seychelles": "SC",
  "sd": "SD",
  "sudan": "SD",
  "se": "SE",
  "sweden": "SE",
  "sg": "SG",
  "singapore": "SG",
  "si": "SI",
  "slovenia": "SI",
  "sk": "SK",
  "slovakia": "SK",
  "sierra leone": "SL",
  "sl": "SL",
  "san marino": "SM",
  "sm": "SM",
  "senegal": "SN",
  "sn": "SN",
  "so": "SO",
  "somalia": "SO",
  "sr": "SR",
  "suriname": "SR",
  "south sudan": "SS",
  "ss": "SS",
  "sao tome and principe": "ST",
  "st": "ST",
  "el salvador": "SV",
  "sv": "SV",
  "sy": "SY",
  "syria": "SY",
  "eswatini": "SZ",
  "sz": "SZ",
  "chad": "TD",
  "td": "TD",
  "tg": "TG",
  "togo": "TG",
  "th": "TH",
  "thailand": "TH",
  "tajikistan": "TJ",
  "tj": "TJ",
  "timor-leste": "TL",
  "tl": "TL",
  "tm": "TM",
  "turkmenistan": "TM",
  "tn": "TN",
  "tunisia": "TN",
  "to": "TO",
  "tonga": "TO",
  "tr": "TR",
  "turkey": "TR",
  "trinidad and tobago": "TT",
  "tt": "TT",
  "tuvalu": "TV",
  "tv": "TV",
  "taiwan": "TW",
  "tw": "TW",
  "tanzania": "TZ",
  "tz": "TZ",
  "ua": "UA",
  "ukraine": "UA",
  "ug": "UG",
  "uganda": "UG",
  "united states": "US",
  "us": "US",
  "uruguay": "UY",
  "uy": "UY",
  "uz": "UZ",
  "uzbekistan": "UZ",
  "holy see (vatican city)": "VA",
  "va": "VA",
  "saint vincent and the grenadines": "VC",
  "vc": "VC",
  "ve": "VE",
  "venezuela": "VE",
  "vietnam": "VN",
  "vn": "VN",
  "vanuatu": "VU",
  "vu": "VU",
  "samoa": "WS",
  "ws": "WS",
  "ye": "YE",
  "yemen": "YE",
  "south africa": "ZA",
  "za": "ZA",
  "zambia": "ZM",
  "zm": "ZM",
  "zimbabwe": "ZW",
  "zw": "ZW",
};

/**
 * Accepts a country name or an ISO code and always returns an ISO code.
 *
 * Falls back to upper-casing the input when nothing matches, which preserves
 * the previous behaviour for anything genuinely unrecognised rather than
 * returning an empty string and losing the value entirely.
 */
export function resolveCountryCode(rawCountry: string | undefined | null): string {
  if (!rawCountry) return "";
  const key = rawCountry.trim().toLowerCase();
  return COUNTRY_NAME_TO_CODE[key] ?? rawCountry.trim().toUpperCase();
}
