/**
 * Points the mobile app at a real Firebase project instead of the emulator.
 *
 * Every EAS build profile carried EXPO_PUBLIC_USE_FIREBASE_EMULATOR=true, so
 * every build ever installed talked to an emulator on one laptop. On anyone
 * else's phone that is an app with no backend behind it, which is exactly how it
 * kept being reported.
 *
 * This reads the real web SDK config from the project and writes it into two
 * places: .env.dev for local runs, and an android-dev profile in eas.json for
 * builds. It does not touch the existing emulator profiles — those are still
 * the right thing for local work.
 *
 *   node write-dev-env.js --project platform-dev --mobile ../multivendor-marketplace-mobile/expo
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const args = process.argv.slice(2);
const argOf = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : fallback;
};

const PROJECT = argOf("project", "platform-dev");
const MOBILE = path.resolve(argOf("mobile", path.join(__dirname, "../../multivendor-marketplace-mobile/expo")));

// platform-dev has three registered WEB apps (mobile, website+CMS, vendor
// portal) — `apps:sdkconfig WEB` with no app id is ambiguous between them and
// the CLI refuses to guess, failing with "must specify an app id". This
// script exists specifically to point the mobile app at dev (per the module
// doc above), so it needs the mobile app's id, not whichever app the CLI
// would otherwise default to.
const APP_ID = argOf("app", "1:YOUR_PROJECT_NUMBER:web:0ddfecd6c14d01a69c0e66");

function sdkConfig() {
  // --json keeps this parseable; the human-readable form varies between CLI
  // versions and would break on upgrade.
  // shell: true is required on Windows. Node refuses to spawn .cmd files
  // directly since the batch-file argument injection fix, failing with EINVAL.
  // Every argument here is a literal defined in this file — no caller input
  // reaches the command line, so going through a shell introduces nothing.
  const isWin = process.platform === "win32";
  const raw = execFileSync(
    isWin ? "firebase.cmd" : "firebase",
    ["apps:sdkconfig", "WEB", APP_ID, "--project", PROJECT, "--json"],
    { encoding: "utf8", maxBuffer: 10 * 1024 * 1024, shell: isWin }
  );
  const parsed = JSON.parse(raw);
  const config = parsed?.result?.sdkConfig;
  if (!config?.apiKey) {
    throw new Error(
      `No web app found in ${PROJECT}. Create one in the Firebase console ` +
      `(Project settings > Your apps > Web) and run this again.`
    );
  }
  return config;
}

function main() {
  const c = sdkConfig();

  const env = {
    EXPO_PUBLIC_USE_FIREBASE_EMULATOR: "false",
    EXPO_PUBLIC_FIREBASE_API_KEY: c.apiKey,
    EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN: c.authDomain,
    EXPO_PUBLIC_FIREBASE_PROJECT_ID: c.projectId,
    EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET: c.storageBucket,
    EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: c.messagingSenderId,
    EXPO_PUBLIC_FIREBASE_APP_ID: c.appId,
  };

  // .env.dev rather than .env: .env is gitignored and holds whatever the
  // developer is currently pointed at, and overwriting it would silently move
  // someone off the emulator mid-task.
  const envPath = path.join(MOBILE, ".env.dev");
  fs.writeFileSync(
    envPath,
    `# Generated by scripts/write-dev-env.js against ${PROJECT}.\n` +
    `# Copy over .env to run locally against dev:  cp .env.dev .env\n` +
    Object.entries(env).map(([k, v]) => `${k}=${v}`).join("\n") + "\n"
  );
  console.log(`Wrote ${envPath}`);

  const easPath = path.join(MOBILE, "eas.json");
  const eas = JSON.parse(fs.readFileSync(easPath, "utf8"));

  // A build profile, not a secret store. These are public client identifiers —
  // an API key here identifies the project, it does not authorise anything.
  // Access is decided by security rules and App Check, which is why committing
  // them is both normal and safe.
  eas.build["android-dev"] = {
    distribution: "internal",
    android: { buildType: "apk" },
    env,
  };
  eas.build["ios-simulator-dev"] = {
    distribution: "internal",
    ios: { simulator: true, resourceClass: "m-medium" },
    env,
  };

  fs.writeFileSync(easPath, JSON.stringify(eas, null, 2) + "\n");
  console.log(`Added android-dev and ios-simulator-dev profiles to ${easPath}`);
  console.log(`\nBoth point at ${PROJECT}. The existing profiles still point at`);
  console.log(`the emulator, which is correct for local work.`);
}

main();
